"""
Email Notification System
Sends notifications to subscribers when new milestones are added
"""

import os
import json
from typing import List, Dict
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from google.oauth2 import service_account
from googleapiclient.discovery import build

class NotificationSystem:
    def __init__(self):
        # For Google Sheets integration (get subscribers)
        self.google_sheet_id = os.getenv('GOOGLE_SHEET_ID')
        self.google_creds_json = os.getenv('GOOGLE_CREDENTIALS_JSON')
        
        # For email sending (multiple options)
        self.email_provider = os.getenv('EMAIL_PROVIDER', 'sendgrid')  # sendgrid, ses, smtp
        self.sendgrid_api_key = os.getenv('SENDGRID_API_KEY')
        self.smtp_host = os.getenv('SMTP_HOST')
        self.smtp_port = int(os.getenv('SMTP_PORT', '587'))
        self.smtp_user = os.getenv('SMTP_USER')
        self.smtp_password = os.getenv('SMTP_PASSWORD')
        self.from_email = os.getenv('FROM_EMAIL', 'noreply@mlmilestones.com')
        
    def get_subscribers(self) -> List[str]:
        """Get subscriber emails from Google Sheets"""
        try:
            # Load credentials
            if self.google_creds_json:
                creds_dict = json.loads(self.google_creds_json)
                credentials = service_account.Credentials.from_service_account_info(
                    creds_dict,
                    scopes=['https://www.googleapis.com/auth/spreadsheets.readonly']
                )
                
                # Build service
                service = build('sheets', 'v4', credentials=credentials)
                
                # Get subscriber emails
                result = service.spreadsheets().values().get(
                    spreadsheetId=self.google_sheet_id,
                    range='Subscribers!A:A'
                ).execute()
                
                values = result.get('values', [])
                # Skip header row, get emails
                emails = [row[0] for row in values[1:] if row]
                print(f"Found {len(emails)} subscribers")
                return emails
            else:
                print("⚠ No Google credentials configured")
                return []
                
        except Exception as e:
            print(f"Error getting subscribers: {e}")
            return []
    
    def create_email_html(self, milestones: List[Dict]) -> str:
        """Create HTML email for new milestones"""
        
        milestone_html = ""
        for m in milestones:
            importance_emoji = {
                'pivotal': '🔴',
                'major': '🟡',
                'notable': '🟢'
            }.get(m['importance'], '⚪')
            
            milestone_html += f"""
            <div style="margin: 20px 0; padding: 15px; background: #f5f5f5; border-radius: 8px;">
                <h3 style="margin: 0 0 10px 0;">
                    {importance_emoji} {m['name']}
                </h3>
                <p style="margin: 5px 0; color: #666;">
                    {m['detail']}
                </p>
                <p style="margin: 10px 0 0 0;">
                    <a href="{m['link']}" style="color: #0066cc; text-decoration: none;">
                        Read more →
                    </a>
                    <span style="color: #999; margin-left: 10px;">
                        {m['date']}
                    </span>
                </p>
            </div>
            """
        
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <h2 style="color: #333;">🤖 New ML Milestones Discovered</h2>
            <p style="color: #666;">
                The AI curation system has identified {len(milestones)} new milestone(s) in ML progress:
            </p>
            
            {milestone_html}
            
            <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px;">
                <p>View the complete timeline at <a href="https://aiprogress.today" style="color: #0066cc;">aiprogress.today</a></p>
                <p>This notification was automatically generated by an AI agent tracking ML progress.</p>
            </div>
        </body>
        </html>
        """
        return html
    
    def send_email_sendgrid(self, to_email: str, subject: str, html_content: str):
        """Send email via SendGrid"""
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail
        
        message = Mail(
            from_email=self.from_email,
            to_emails=to_email,
            subject=subject,
            html_content=html_content
        )
        
        try:
            sg = SendGridAPIClient(self.sendgrid_api_key)
            response = sg.send(message)
            return response.status_code == 202
        except Exception as e:
            print(f"SendGrid error: {e}")
            return False
    
    def send_email_smtp(self, to_email: str, subject: str, html_content: str):
        """Send email via SMTP"""
        try:
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = self.from_email
            msg['To'] = to_email
            
            html_part = MIMEText(html_content, 'html')
            msg.attach(html_part)
            
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_password)
                server.send_message(msg)
            
            return True
        except Exception as e:
            print(f"SMTP error: {e}")
            return False
    
    def notify_subscribers(self, new_milestones: List[Dict]) -> int:
        """Send notifications to all subscribers about new milestones"""
        if not new_milestones:
            print("No milestones to notify about")
            return 0
        
        subscribers = self.get_subscribers()
        if not subscribers:
            print("No subscribers to notify")
            return 0
        
        subject = f"🤖 {len(new_milestones)} New ML Milestone(s) Discovered"
        html_content = self.create_email_html(new_milestones)
        
        sent_count = 0
        print(f"\nSending notifications to {len(subscribers)} subscriber(s)...")
        
        for email in subscribers:
            try:
                if self.email_provider == 'sendgrid':
                    success = self.send_email_sendgrid(email, subject, html_content)
                else:
                    success = self.send_email_smtp(email, subject, html_content)
                
                if success:
                    sent_count += 1
                    print(f"✓ Sent to {email}")
                else:
                    print(f"✗ Failed to send to {email}")
                    
            except Exception as e:
                print(f"✗ Error sending to {email}: {e}")
        
        print(f"\n✓ Sent {sent_count}/{len(subscribers)} notifications")
        return sent_count

if __name__ == "__main__":
    notifier = NotificationSystem()
    
    # Load new milestones
    try:
        with open('evaluated_milestones.json', 'r') as f:
            milestones = json.load(f)
        
        if milestones:
            notifier.notify_subscribers(milestones)
        else:
            print("No milestones to notify about")
            
    except FileNotFoundError:
        print("No evaluated_milestones.json found")
